//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlatFiles.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlatFiles.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property selector did not select a property..
        /// </summary>
        internal static string BadPropertySelector {
            get {
                return ResourceManager.GetString("BadPropertySelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to define a column with a null or blank name..
        /// </summary>
        internal static string BlankColumnName {
            get {
                return ResourceManager.GetString("BlankColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to operate on a closed FlatFileDataReader..
        /// </summary>
        internal static string ClosedDataReader {
            get {
                return ResourceManager.GetString("ClosedDataReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to add a column to a schema where the same name already exists..
        /// </summary>
        internal static string DuplicateColumnName {
            get {
                return ResourceManager.GetString("DuplicateColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record separator cannot be null or empty..
        /// </summary>
        internal static string EmptyRecordSeparator {
            get {
                return ResourceManager.GetString("EmptyRecordSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column separator cannot be null or empty..
        /// </summary>
        internal static string EmptySeparator {
            get {
                return ResourceManager.GetString("EmptySeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open the specified file..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record did not meet the length requirements specified in the schema. Record {0}..
        /// </summary>
        internal static string FixedLengthRecordTooShort {
            get {
                return ResourceManager.GetString("FixedLengthRecordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an invalid fixed width column alignment..
        /// </summary>
        internal static string InvalidAlignment {
            get {
                return ResourceManager.GetString("InvalidAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column count cannot be negative..
        /// </summary>
        internal static string InvalidColumnCount {
            get {
                return ResourceManager.GetString("InvalidColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to define a column with a negative index..
        /// </summary>
        internal static string InvalidColumnIndex {
            get {
                return ResourceManager.GetString("InvalidColumnIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to define a column with a negative width..
        /// </summary>
        internal static string InvalidColumnWidth {
            get {
                return ResourceManager.GetString("InvalidColumnWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The row count cannot be zero or negative..
        /// </summary>
        internal static string InvalidEndingRow {
            get {
                return ResourceManager.GetString("InvalidEndingRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an invalid record format. Record {0}..
        /// </summary>
        internal static string InvalidRecordFormatNumber {
            get {
                return ResourceManager.GetString("InvalidRecordFormatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The starting column was not a sequence of characters..
        /// </summary>
        internal static string InvalidStartingColumn {
            get {
                return ResourceManager.GetString("InvalidStartingColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The starting row cannot be zero or negative..
        /// </summary>
        internal static string InvalidStartingRow {
            get {
                return ResourceManager.GetString("InvalidStartingRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an invalid overflow truncation policy..
        /// </summary>
        internal static string InvalidTruncationPolicy {
            get {
                return ResourceManager.GetString("InvalidTruncationPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the worksheet read from or write to must be provided..
        /// </summary>
        internal static string InvalidWorksheetName {
            get {
                return ResourceManager.GetString("InvalidWorksheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt to view values was made after all of the records were read..
        /// </summary>
        internal static string NoMoreRecords {
            get {
                return ResourceManager.GetString("NoMoreRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to work with a parser after an invalid record was encountered..
        /// </summary>
        internal static string ReadingWithErrors {
            get {
                return ResourceManager.GetString("ReadingWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt to view values was made before reading the first record..
        /// </summary>
        internal static string ReadNotCalled {
            get {
                return ResourceManager.GetString("ReadNotCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered a null while parsing a required column..
        /// </summary>
        internal static string RequiredColumnNull {
            get {
                return ResourceManager.GetString("RequiredColumnNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column and record separator are the same string..
        /// </summary>
        internal static string SameSeparator {
            get {
                return ResourceManager.GetString("SameSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to retrieve the schema when none was extracted or provided..
        /// </summary>
        internal static string SchemaNotDefined {
            get {
                return ResourceManager.GetString("SchemaNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record did not have the number of columns specified in the schema. Record {0}..
        /// </summary>
        internal static string SeparatedValueRecordWrongNumberOfColumns {
            get {
                return ResourceManager.GetString("SeparatedValueRecordWrongNumberOfColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A syntax error was encountered: Unmatched quote..
        /// </summary>
        internal static string UnmatchedQuote {
            get {
                return ResourceManager.GetString("UnmatchedQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wrong number of values were passed..
        /// </summary>
        internal static string WrongNumberOfValues {
            get {
                return ResourceManager.GetString("WrongNumberOfValues", resourceCulture);
            }
        }
    }
}
